### ISSUE TITLE
NVIDIA Compiler Integration

### ISSUE THREAD

**Issue by gha3mi** [fortran-lang/setup-fortran#52]
Hello

I have added the NVIDIA compiler to setup and updated actions and workflows. Before sending a PR, I would like to inform you here. Please take a look at: https://github.com/gha3mi/setup-fortran

Best regards
Ali

**Comment by jalvesz** [comment]
Hi, I'm setting up a workflow depending on setup-fortran and I'm having an issue with nvfortran that seems to be related with the installation https://github.com/jalvesz/fast_math/actions/runs/7521896804/job/20473274032
```sh
Run fortran-lang/setup-fortran@v1
Run action_path=$(echo '//home/runner/work/_actions/fortran-lang/setup-fortran/v1' | sed -e 's/\\/\//g' -e 's/://')
+ compiler=nvidia-hpc
++ uname -s
++ tr '[:upper:]' '[:lower:]'
+ platform=linux
+ case $compiler in
+ exit 1
Error: Process completed with exit code 1.
```
Has anyone seen this kind of issues?
Here my setup file https://github.com/jalvesz/fast_math/blob/main/.github/workflows/ci.yml

**Comment by gha3mi** [comment]
Hi,
The nvfortran setup has been recently tested and merged into the main branch, also it is not available in version 1 of setup-fortran. Perhaps before the next release, you can give it a try using `fortran-lang/setup-fortran@main` or `fortran-lang/setup-fortran@master`.

**Comment by wpbonelli** [comment]
We should make a new release soon, it would be good to get #51 in for that though.

**Comment by jalvesz** [comment]
>fortran-lang/setup-fortran@main

Nice!! this worked! thanks

**Comment by jalvesz** [comment]
Hi,
So with the proposed solution nvfortran was installed, but for some reason, even though the environment vars were set, at compile time it was still looking for gfortran. you can see the log here https://github.com/jalvesz/fast_math/actions/runs/7522194607/job/20473898816
and the error
```sh
<ERROR> Compilation failed for object " src_fast_erf.f90.o "
<ERROR> stopping due to failed compilation
STOP 1

gfortran: error: gfortran does not support -E without -cpp
Error: Process completed with exit code 1.
```
Since I'm using `fpm` to run the tests, I had to add the compiler explicitly like this:
```yml
- run: |
          fpm test --compiler ${{ env.FC }} --flag "${{ join(matrix.toolchain.flags, ' ') }}"
```

**Comment by gha3mi** [comment]
As you mentioned, when using fpm, you need to add `--compiler ${{ env.FC }}`. However, in your `ci.yml`, it is not included. Doesn't this solve the problem?

**Comment by jalvesz** [comment]
I added it in a parallel branch to test because I was polluting the commits in the main branch, here is my latest version `https://github.com/jalvesz/fast_math/blob/jalvesz-patch-1/.github/workflows/ci.yml`

Just wanted to signal this particularity with `fpm`... maybe this could be automated by setting also FPM_FC=FC, FPM_CXX=CXX, FPM_CC=CC ?

**Comment by gha3mi** [comment]
> FPM_FC=FC, FPM_CXX=CXX, FPM_CC=CC

I think it's a good idea to set environment variables for fpm within setup-fortran.

**Comment by wpbonelli** [comment]
Possibly relevant:

- https://github.com/fortran-lang/fpm/issues/576
- https://github.com/fortran-lang/fpm/pull/608

I'm not clear why the PR was closed or if such an option is still planned, maybe there was backchannel discussion @awvwgk can fill in. But setting fpm variables seems reasonable in any case.
