### ISSUE TITLE
Support devcontainer 

### ISSUE THREAD

**Issue by luwangshell** [fortran-lang/setup-fortran#54]
Hello! I have been using GitHub Codespaces (which uses the devcontainer under the hood) and just wondering if any plan to implemenet a devcontainer which contains the Fortran setup and tooling? Microsoft has an opensource repo for different types of devcontainers supporting different tech stacks, but there is no fortran atm. https://github.com/microsoft/vscode-dev-containers

Thank you!
Lu

**Comment by wpbonelli** [comment]
There is no plan at the moment, I'm not sure how any such integration would work. If you are defining a container to use with codespaces, it seems more straightforward to install a Fortran toolchain of your choice in it and then [run actions with the same container definition](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container). But I know very little about codespaces, if I am missing something please clarify

**Comment by antonimmo** [comment]
@luwangshell I tried to do the same about a year ago, even tried to build a Docker image I can start from. I made it work for gfortran, but it doesn't work for Intel because HPC toolkit makes the image way too big (>20 or 25 GB) for using on Codespaces. However, it does work locally, I which case I can share it.
